### ISSUE TITLE
1N4148W footprints too small

### ISSUE THREAD

**Issue by 7h0ma5** [LibreSolar/BMS-5s#9]
I'm currently building the control PCB of the BMS-5s and noticed that the SOD-323 footprints of D6, D8 and D13 are too small for 1N4148W diodes. According to the [datasheet](https://datasheet.octopart.com/1N4148W-7-F-Diodes-Inc.-datasheet-8327071.pdf) they should have a SOD-123 footprint. Diodes of the type 1N4148WS would fit the SOD-323 footprint, but they have a lower power dissipation and surge current rating.

**Comment by martinjaeger** [comment]
Thanks. I actually built up my boards with 1N4148WS, but didn't realize that they were not correctly specified as I have both in electronics parts boxes.

KiCad schematic is now fixed.
